### ISSUE TITLE
Login Encryption

### ISSUE THREAD

**Issue by blunderedbishop** [plewin/tp-link-modem-router#1]
Hello! I have the same router as you, the TP-Link Archer MR600. I'm trying to build a python API to interact with it but I'm having trouble with how the `data` and `sign` parameters are encrypted when sending the POST request to `/cgi/login` to authenticate. I've tried to take a look at `routerEncryption.mjs ` but since I have no experience with JS or encryption (sorry) I can't really figure out what's happening. I was wondering if you were willing to give me a quick explanation, if it is even possible. Thanks a lot!

**Comment by plewin** [comment]
@blunderedbishop I'm sorry somehow I missed the notification.

Hope you managed to do what you wanted. Are you still working on it ?

I implemented the whole thing in javascript to reuse the same library as the router to be cheaper to implement. It was quite complicated to make it work.

**Comment by blunderedbishop** [comment]
Hey, don't worry about it, thanks for the answer.

I eventually gave up because I couldn't really figure out how the password
was being encoded, but it was my first time trying to reverse engineer
something like that, so no worry. It was nothing important.

Cheers!

**Comment by plewin** [comment]
I'm closing this thread as it is basically solved
A note from what I recall, this particular line of modem routers have a low level non standard difference in some data padding and encoding that makes most rsa implementations incompatibles.
Seems someone managed to implement it correctly in python directly from the browser js implementation https://github.com/hercule115/TPLink-Archer so that should be worth a try if someone needs a python implementation

**Comment by Muhammadyusuf96** [comment]
@mehmetbeyHZ how did you figured out? What was your hardware and software version?
